name: Main Workflow
on:
  pull_request:
  push:
      branches:
        - 'main'
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          yarn
          yarn build
          yarn lint
