name: PR Workflow
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          yarn
          yarn build
